use thematic's approach to testing

diff --git a/.github/workflows/R-CMD-check.yaml b/.github/workflows/R-CMD-check.yaml
--- a/.github/workflows/R-CMD-check.yaml
+++ b/.github/workflows/R-CMD-check.yaml
@@ -104,26 +104,36 @@ jobs:
           pkgs <- installed.packages()[, "Package"]
           sessioninfo::session_info(pkgs, include_base = TRUE)
         shell: Rscript {0}
-
-      - name: Check
-        env:
-          _R_CHECK_CRAN_INCOMING_: false
+        
+        # Run test() before R CMD check since, for some reason, rcmdcheck::rcmdcheck() skips vdiffr tests
+      - name: Run Tests
         run: |
-          options(crayon.enabled = TRUE)
-          rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
+          if (!require(devtools)) install.packages("devtools")
+          devtools::install()
+          res <- devtools::test()
+          df <- as.data.frame(res)
+          if (sum(df$failed) > 0 || any(df$error)) stop("GHA CI tests failed")
         shell: Rscript {0}
 
-      - name: Show testthat output
-        if: always()
-        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
-        shell: bash
+      # Run check with --no-tests since we ran them abve
+      - name: Check
+        run: |
+          options(crayon.enabled = TRUE)
+          rcmdcheck::rcmdcheck(args = c("--no-tests", "--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
+        shell: Rscript {0}
 
+      # Upload the whole pkg since tests where run with devtools::test()
       - name: Upload check results
         if: failure()
-        uses: actions/upload-artifact@main
+        uses: actions/upload-artifact@master
         with:
-          name: ${{ matrix.config.os }}-r${{ matrix.config.r }}-results
-          path: check
+          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
+          path: ./
+
+      #- name: Show testthat output
+      #  if: always()
+      #  run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
+      #  shell: bash
 
       - name: Don't use tar from old Rtools to store the cache
         if: ${{ runner.os == 'Windows' && startsWith(steps.install-r.outputs.installed-r-version, '3.6' ) }}
